name: Continuos Integration
on:  
 push:
   tags: [ 'release/**' ]
   branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
  test:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: unit test
        #TODO: CI must use actions instead of Makefile
        run: make install
  build:
    name: Build system
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Run Go build
        run: |
          echo "Build"
